<?php

/**
 * BaseAbout
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $adress
 * @property string $phone
 * @property string $fax
 * @property string $icq
 * @property string $skype
 * @property string $email
 * @property string $description
 * @property string $description_on_main
 * @property string $keywords
 * @property string $title
 * @property string $copyright
 * 
 * @method string getAdress()              Returns the current record's "adress" value
 * @method string getPhone()               Returns the current record's "phone" value
 * @method string getFax()                 Returns the current record's "fax" value
 * @method string getIcq()                 Returns the current record's "icq" value
 * @method string getSkype()               Returns the current record's "skype" value
 * @method string getEmail()               Returns the current record's "email" value
 * @method string getDescription()         Returns the current record's "description" value
 * @method string getDescriptionOnMain()   Returns the current record's "description_on_main" value
 * @method string getKeywords()            Returns the current record's "keywords" value
 * @method string getTitle()               Returns the current record's "title" value
 * @method string getCopyright()           Returns the current record's "copyright" value
 * @method About  setAdress()              Sets the current record's "adress" value
 * @method About  setPhone()               Sets the current record's "phone" value
 * @method About  setFax()                 Sets the current record's "fax" value
 * @method About  setIcq()                 Sets the current record's "icq" value
 * @method About  setSkype()               Sets the current record's "skype" value
 * @method About  setEmail()               Sets the current record's "email" value
 * @method About  setDescription()         Sets the current record's "description" value
 * @method About  setDescriptionOnMain()   Sets the current record's "description_on_main" value
 * @method About  setKeywords()            Sets the current record's "keywords" value
 * @method About  setTitle()               Sets the current record's "title" value
 * @method About  setCopyright()           Sets the current record's "copyright" value
 * 
 * @package    cmatis
 * @subpackage model
 * @author     BulgakowS <bulgakows@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAbout extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('about');
        $this->hasColumn('adress', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('phone', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('fax', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('icq', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('skype', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 15000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 15000,
             ));
        $this->hasColumn('description_on_main', 'string', 15000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 15000,
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('copyright', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'adress',
              1 => 'description',
              2 => 'description_on_main',
              3 => 'metatags',
              4 => 'keywords',
              5 => 'title',
              6 => 'text',
             ),
             ));
        $this->actAs($i18n0);
    }
}