<?php

/**
 * BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $url
 * @property integer $level
 * @property integer $parent_id
 * @property integer $position
 * @property string $description
 * @property boolean $on_main
 * @property boolean $in_menu
 * @property integer $templ
 * @property boolean $lan_enable
 * @property string $tags
 * @property Doctrine_Collection $Article
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getUrl()         Returns the current record's "url" value
 * @method integer             getLevel()       Returns the current record's "level" value
 * @method integer             getParentId()    Returns the current record's "parent_id" value
 * @method integer             getPosition()    Returns the current record's "position" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method boolean             getOnMain()      Returns the current record's "on_main" value
 * @method boolean             getInMenu()      Returns the current record's "in_menu" value
 * @method integer             getTempl()       Returns the current record's "templ" value
 * @method boolean             getLanEnable()   Returns the current record's "lan_enable" value
 * @method string              getTags()        Returns the current record's "tags" value
 * @method Doctrine_Collection getArticle()     Returns the current record's "Article" collection
 * @method Category            setName()        Sets the current record's "name" value
 * @method Category            setUrl()         Sets the current record's "url" value
 * @method Category            setLevel()       Sets the current record's "level" value
 * @method Category            setParentId()    Sets the current record's "parent_id" value
 * @method Category            setPosition()    Sets the current record's "position" value
 * @method Category            setDescription() Sets the current record's "description" value
 * @method Category            setOnMain()      Sets the current record's "on_main" value
 * @method Category            setInMenu()      Sets the current record's "in_menu" value
 * @method Category            setTempl()       Sets the current record's "templ" value
 * @method Category            setLanEnable()   Sets the current record's "lan_enable" value
 * @method Category            setTags()        Sets the current record's "tags" value
 * @method Category            setArticle()     Sets the current record's "Article" collection
 * 
 * @package    cmatis
 * @subpackage model
 * @author     BulgakowS <bulgakows@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('level', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             'default' => 0,
             ));
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('position', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             'default' => 1,
             ));
        $this->hasColumn('description', 'string', 50000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 50000,
             ));
        $this->hasColumn('on_main', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('in_menu', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('templ', 'integer', null, array(
             'type' => 'integer',
             'default' => 1,
             ));
        $this->hasColumn('lan_enable', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('tags', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Article', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'description',
              2 => 'lan_enable',
              3 => 'tags',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}