<?php

/**
 * Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cmatis
 * @subpackage model
 * @author     BulgakowS <bulgakows@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Category extends BaseCategory
{
    public function getSubs()
    {
        $cu = substr(sfContext::getInstance()->getUser()->getCulture(), 0, 2);
        return CategoryTable::getSubs($this->getId(), $cu);
    }
    
    public function isSubcategory()
    {
        return $this->parent_id != 0;
    }
    
    public function getLvl($lvl = 0, $cat = false)
    {
        $cat = $cat ? $cat : $this;
        if ( $cat->getParentId() == 0 ) {
            return $lvl;
        } else {
            $this->getLvl($lvl++, $this);
        }
    }
    
    public function getLastArticles($lim = 5){
        return Doctrine::getTable('Article')->createQuery('a')
                ->addWhere('category_id = ?', $this->getId())
                ->orderBy('updated_at')
                ->limit($lim)
                ->execute();
    }
}
