<?php

/**
 * Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cmatis
 * @subpackage model
 * @author     BulgakowS <bulgakows@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Category extends BaseCategory
{
    private $lvl = 0;
    
    public function getSubs()
    {
        $cu = substr(sfContext::getInstance()->getUser()->getCulture(), 0, 2);
        return CategoryTable::getSubs($this->getId(), $cu);
    }
    
    public function isSubcategory()
    {
        return (bool)($this->parent_id != 0);
    }
    
    public static function getCategoryById($id) 
    {
        return CategoryTable::getById($id);
    }
    
    public function updateLevel()
    {
        if ( $this->parent_id != 0 ) {
            $this->setLevel( $this->getParent()->getLevel() + 1 );
            $this->save();
        } else {
            $this->setLevel(0);
            $this->save();
        }
    }
    
    public function getParent()
    {
        return Doctrine::getTable('Category')->find( $this->parent_id );
    }

    public function getLastArticles($lim = 5){
        return ArticleTable::getQuery()
                ->addWhere('a.category_id = ?', $this->getId())
                ->orderBy('updated_at')
                ->limit($lim)
                ->execute();
    }
}
