<?php

/**
 * ReclameTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReclameTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReclameTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Reclame');
    }
}