<?php

/**
 * SettingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SettingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SettingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Setting');
    }
    
    public static function getSetting() 
    {
        return Doctrine::getTable('setting')->find(1);
    }
    
    public static function getNews() 
    {
        $sett = self::getSetting();
        return $sett ? $sett->getNews() : 5;
    }
    
    public static function getNewsByCategory() 
    {
        $sett = self::getSetting();
        return $sett ? $sett->getNewsByCategory() : 3;
    }
    
    public static function getCategoriesOnMain() 
    {
        $sett = self::getSetting();
        return $sett ? $sett->getCategoriesOnMain() : 3;
    }
    
}