<?php

/**
 * Setting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cmatis
 * @subpackage model
 * @author     BulgakowS <bulgakows@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Setting extends BaseSetting
{

    
}
