<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/03/04 23:14:44

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=cmatis',
  'username' => 'root',
  'password' => 'root',
  'attributes' => 
  array (
    'DEFAULT_TABLE_TYPE' => 'INNODB',
    'DEFAULT_TABLE_CHARSET' => 'utf8',
    'DEFAULT_TABLE_COLLATE' => 'utf8_general_ci',
  ),
  'name' => 'doctrine',
)),);
